/**
 * Record category rules shared by UI and server.
 * Client components import from here. Server code may import from
 * `@/lib/record-config` (re-exports this module).
 */

export type RecordCategoryConfig = {
  label: string;
  titlePlaceholder: string;
  requiredFields: string[];
  visibleFields: string[];
  requiresAmount: boolean;
  requiresBusinessJustification: boolean;
  suggestsVendor: boolean;
  showsInvoiceNumber: boolean;
  showsPolicyException: boolean;
  requiresNeededByDate: boolean;
  defaultCloseReasons: string[];
};

export const RECORD_CATEGORY_CONFIG: Record<string, RecordCategoryConfig> = {
  BUDGET_REQUEST: {
    label: "Budget Request",
    titlePlaceholder: "e.g. Q3 Marketing Budget Request",
    requiredFields: ["title", "requestedAmount", "currencyCode", "businessJustification"],
    visibleFields: [
      "title",
      "requestedAmount",
      "currencyCode",
      "businessJustification",
      "departmentName",
      "costCenterCode",
      "neededByDate",
      "description",
    ],
    requiresAmount: true,
    requiresBusinessJustification: true,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: true,
    requiresNeededByDate: false,
    defaultCloseReasons: [
      "APPROVED_AND_COMPLETED",
      "REJECTED",
      "WITHDRAWN_BY_REQUESTER",
      "NO_ACTION_REQUIRED",
      "OTHER",
    ],
  },
  SPEND_APPROVAL: {
    label: "Spend Approval",
    titlePlaceholder: "e.g. Software License Renewal - Figma",
    requiredFields: ["title", "requestedAmount", "currencyCode", "businessJustification"],
    visibleFields: [
      "title",
      "requestedAmount",
      "currencyCode",
      "businessJustification",
      "vendorName",
      "payeeName",
      "neededByDate",
      "purchaseOrderRef",
      "description",
    ],
    requiresAmount: true,
    requiresBusinessJustification: true,
    suggestsVendor: true,
    showsInvoiceNumber: false,
    showsPolicyException: true,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "WITHDRAWN_BY_REQUESTER", "OTHER"],
  },
  VENDOR_PAYMENT_REQUEST: {
    label: "Vendor Payment Request",
    titlePlaceholder: "e.g. Payment to Acme Corp - Invoice #1234",
    requiredFields: ["title", "requestedAmount", "currencyCode", "vendorName", "neededByDate"],
    visibleFields: [
      "title",
      "requestedAmount",
      "currencyCode",
      "vendorName",
      "payeeName",
      "invoiceNumber",
      "neededByDate",
      "purchaseOrderRef",
      "description",
    ],
    requiresAmount: true,
    requiresBusinessJustification: false,
    suggestsVendor: true,
    showsInvoiceNumber: true,
    showsPolicyException: false,
    requiresNeededByDate: true,
    defaultCloseReasons: [
      "PAID_OR_SETTLED",
      "REJECTED",
      "WITHDRAWN_BY_REQUESTER",
      "DUPLICATE",
      "OTHER",
    ],
  },
  REIMBURSEMENT: {
    label: "Reimbursement",
    titlePlaceholder: "e.g. Travel Reimbursement - Miami Conference",
    requiredFields: ["title", "requestedAmount", "currencyCode", "payeeName", "businessJustification"],
    visibleFields: [
      "title",
      "requestedAmount",
      "currencyCode",
      "payeeName",
      "businessJustification",
      "costCenterCode",
      "neededByDate",
      "description",
    ],
    requiresAmount: true,
    requiresBusinessJustification: true,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: false,
    requiresNeededByDate: false,
    defaultCloseReasons: ["PAID_OR_SETTLED", "REJECTED", "WITHDRAWN_BY_REQUESTER", "OTHER"],
  },
  FINANCIAL_EXCEPTION: {
    label: "Financial Exception",
    titlePlaceholder: "e.g. Over-budget approval for Q4 hiring",
    requiredFields: ["title", "businessJustification", "policyExceptionReason"],
    visibleFields: [
      "title",
      "businessJustification",
      "policyExceptionReason",
      "requestedAmount",
      "currencyCode",
      "description",
    ],
    requiresAmount: false,
    requiresBusinessJustification: true,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: true,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "WITHDRAWN_BY_REQUESTER", "OTHER"],
  },
  CONTRACT_SCOPE_CHANGE: {
    label: "Contract / Scope Change",
    titlePlaceholder: "e.g. Scope change - Andres Gomez contract amendment",
    requiredFields: ["title", "businessJustification"],
    visibleFields: [
      "title",
      "businessJustification",
      "requestedAmount",
      "currencyCode",
      "contractReference",
      "vendorName",
      "neededByDate",
      "description",
    ],
    requiresAmount: false,
    requiresBusinessJustification: true,
    suggestsVendor: true,
    showsInvoiceNumber: false,
    showsPolicyException: true,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "SUPERSEDED", "OTHER"],
  },
  FORECAST_ADJUSTMENT: {
    label: "Forecast / Allocation Adjustment",
    titlePlaceholder: "e.g. Q4 Headcount Forecast Adjustment",
    requiredFields: ["title", "businessJustification"],
    visibleFields: [
      "title",
      "businessJustification",
      "requestedAmount",
      "currencyCode",
      "departmentName",
      "neededByDate",
      "description",
    ],
    requiresAmount: false,
    requiresBusinessJustification: true,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: false,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "SUPERSEDED", "OTHER"],
  },
  OTHER_FINANCIAL_REQUEST: {
    label: "Other Financial Request",
    titlePlaceholder: "e.g. Ad-hoc financial approval",
    requiredFields: ["title"],
    visibleFields: [
      "title",
      "requestedAmount",
      "currencyCode",
      "businessJustification",
      "vendorName",
      "neededByDate",
      "description",
    ],
    requiresAmount: false,
    requiresBusinessJustification: false,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: true,
    requiresNeededByDate: false,
    defaultCloseReasons: [
      "APPROVED_AND_COMPLETED",
      "REJECTED",
      "WITHDRAWN_BY_REQUESTER",
      "OTHER",
    ],
  },
  BUDGET: {
    label: "Budget",
    titlePlaceholder: "e.g. Budget request",
    requiredFields: ["title"],
    visibleFields: ["title", "requestedAmount", "currencyCode", "description"],
    requiresAmount: false,
    requiresBusinessJustification: false,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: false,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "OTHER"],
  },
  SCOPE_CHANGE: {
    label: "Scope Change",
    titlePlaceholder: "e.g. Scope change request",
    requiredFields: ["title"],
    visibleFields: ["title", "description"],
    requiresAmount: false,
    requiresBusinessJustification: false,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: false,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "OTHER"],
  },
  DECISION: {
    label: "Decision",
    titlePlaceholder: "e.g. Decision request",
    requiredFields: ["title"],
    visibleFields: ["title", "description"],
    requiresAmount: false,
    requiresBusinessJustification: false,
    suggestsVendor: false,
    showsInvoiceNumber: false,
    showsPolicyException: false,
    requiresNeededByDate: false,
    defaultCloseReasons: ["APPROVED_AND_COMPLETED", "REJECTED", "OTHER"],
  },
};
