/** Documented exclusion reasons for assignment candidate snapshots (doc 03 §8). */
export const EXCLUSION_REASONS = {
  AVAILABILITY_AWAY: "AVAILABILITY_AWAY",
  AVAILABILITY_OUT_OF_OFFICE: "AVAILABILITY_OUT_OF_OFFICE",
  AVAILABILITY_ON_LEAVE: "AVAILABILITY_ON_LEAVE",
  AVAILABILITY_PAUSED: "AVAILABILITY_PAUSED",
  INACTIVE_MEMBERSHIP: "INACTIVE_MEMBERSHIP",
  INSUFFICIENT_FINANCE_RESPONSIBILITY: "INSUFFICIENT_FINANCE_RESPONSIBILITY",
  WORKLOAD_CAP_REACHED: "WORKLOAD_CAP_REACHED",
  DELEGATED_OUT: "DELEGATED_OUT",
} as const;

export type ExclusionReason = (typeof EXCLUSION_REASONS)[keyof typeof EXCLUSION_REASONS];
