-- Invalidate all existing embeddings — they were generated by a different model
-- and cannot be compared with text-embedding-3-large vectors.
-- The keyword search fallback ensures chat keeps working during reindex.
UPDATE "KnowledgeBaseChunk" SET embedding = NULL;

-- Drop and recreate HNSW index to ensure clean state
DROP INDEX IF EXISTS "KnowledgeBaseChunk_embedding_hnsw_idx";
DROP INDEX IF EXISTS "KnowledgeBaseChunk_embedding_ivfflat_idx";

CREATE INDEX "KnowledgeBaseChunk_embedding_hnsw_idx"
  ON "KnowledgeBaseChunk"
  USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64)
  WHERE status = 'PUBLISHED'::"KbArticleStatus";
